{
 "title": "Edgeless default dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total number of invocations per function instance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "execution_times_count", "legendFormat": "{{function_id}}" }
   ]
  },
  {
   "title": "Running function instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "function_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Execution time histogram (WIP)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(execution_times_sum[10m]) / rate(execution_times_count[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Function invocations rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by(function_id) (sum by(function_id) (rate(execution_times_count[$__interval])))"
    }
   ]
  }
 ]
}