package edgeless:edgefun

world edgefun {
  
  record fid {
    node: string,
    function: string
  }

  import call-alias: func(alias: string, msg: string)
  import call: func(target: fid, msg: string)
  import log: func(msg: string)
  import slf: func() -> fid
  import delayed-call: func(delayms: u64, target: fid, payload: string)

  export handle-call: func(source: fid, msg: string)
  export handle-init: func(payload: string)
  export handle-stop: func()
}