# SPDX-FileCopyrightText: © 2024 Siemens AG
# SPDX-License-Identifier: MIT

[profile.release]
lto = true
opt-level = "s"

[package]
name = "hello_dda"
version = "0.1.0"
authors = ["Lukasz Zalewski <zalewski.lukasz@siemens.com>"]
edition = "2021"

[lib]
name = "hello_dda"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
edgeless_function = { path = "../../../edgeless_function" }
edgeless_http = { path = "../../../edgeless_http" }
log = "0.4"
