# SPDX-FileCopyrightText: © 2023 Technical University of Munich, Chair of Connected Mobility
# SPDX-License-Identifier: MIT
[workspace]

[profile.release]
lto = true
opt-level = "s"

[package]
name = "edgeless_test_messaging"
version = "0.1.0"
authors = ["Raphael Hetzel <hetzel@in.Technical University of Munich, Chair of Connected Mobility.de"]
edition = "2021"

[lib]
name = "edgeless_test_messaging"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
edgeless_function = { path = "../../../edgeless_function" }
log = "0.4"