[workspace]

[profile.release]
lto = true
opt-level = "s"

[package]
name = "filter_in_range"
version = "0.1.0"
authors = ["Claudio Cicconetti <c.cicconetti@iit.cnr.it>"]
edition = "2021"

[lib]
name = "filter_in_range"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
edgeless_function = { path = "../../../edgeless_function" }
serde = {version="1", features=["derive"] }
serde_json = "1"
log = "0.4"