[server]
server_cert_path = "../../edgeless_api/src/grpc_impl/tls_certs/controller.pem"
server_key_path  = "../../edgeless_api/src/grpc_impl/tls_certs/controller.key"
server_ca_path   = "../../edgeless_api/src/grpc_impl/tls_certs/CA-chain.pem"

[client]
client_cert_path = "../../edgeless_api/src/grpc_impl/tls_certs/orchestrator.pem"
client_key_path  = "../../edgeless_api/src/grpc_impl/tls_certs/orchestrator.key"
client_ca_path   = "../../edgeless_api/src/grpc_impl/tls_certs/CA-chain.pem"
domain_name      = "www.example.com"
#tpm_handle      = ""
