# NOTE: used to generate docker compose templates for larger edgeless clusters automatically
services:
  redis:
    image: redis:latest
    container_name: redis

  edgeless_con:
    image: ghcr.io/edgeless-project/edgeless_con:v1.0.0 
    container_name: edgeless_con
    environment:
      RUST_LOG: info
      CONTROLLER_HOST: 0.0.0.0
      CONTROLLER_PORT: 7001
      DOMAIN_REGISTER_HOST: 0.0.0.0
      DOMAIN_REGISTER_PORT: 7002
    ports:
      - 7001:7001 # needed for the cli
      
  edgeless_orc:
    image: ghcr.io/edgeless-project/edgeless_orc:v1.0.0 
    container_name: edgeless_orc
    depends_on:
      - edgeless_con
      - redis
    environment:
      RUST_LOG: info
      DOMAIN_REGISTER_HOST: edgeless_con
      DOMAIN_REGISTER_PORT: 7002
      SUBSCRIPTION_REFRESH_INTERVAL_SEC: 2
      DOMAIN_ID: domain-1
      ORCHESTRATOR_HOST: 0.0.0.0
      ORCHESTRATOR_PORT: 7003
      NODE_REGISTER_HOST: 0.0.0.0
      NODE_REGISTER_PORT: 7004
      ORCHESTRATION_STRATEGY: Random
      PROXY_TYPE: None
      REDIS_URL: redis://redis:6379
      DATASET_PATH: /dataset
      APPEND: true

  edgeless_node_file_log:
    image: ghcr.io/edgeless-project/edgeless_node:v1.0.0 
    container_name: edgeless_node_file_log
    depends_on:
      - edgeless_orc
    environment:
      RUST_LOG: info
      NODE_ID: 19e80bc9-4ebe-43dc-a2d9-60505c0388ba
      AGENT_HOST: 0.0.0.0
      AGENT_PORT: 7005
      AGENT_URL_ANNOUNCED: http://edgeless_node_file_log:7005
      INVOCATION_HOST: 0.0.0.0
      INVOCATION_PORT: 7002
      INVOCATION_URL_ANNOUNCED: http://edgeless_node_file_log:7002
      NODE_REGISTER_URL: http://edgeless_orc:7004
      SUBSCRIPTION_REFRESH_INTERVAL_SEC: 2
      TELEMETRY_METRICS_HOST: 0.0.0.0
      TELEMETRY_METRICS_PORT: 7003
      TELEMETRY_LOG_LEVEL: info
      TELEMETRY_PERFORMANCE_SAMPLES: true
      WASM_RUNTIME_ENABLED: true
      CONTAINER_RUNTIME_ENABLED: false
      HTTP_INGRESS_HOST: 0.0.0.0
      HTTP_INGRESS_PORT: 7035
      HTTP_INGRESS_PROVIDER: http-ingress-1
      HTTP_EGRESS_PROVIDER: http-egress-1
      FILE_LOG_PROVIDER: file-log-1
      REDIS_PROVIDER: redis-1
      DDA_PROVIDER: dda-1
      KAFKA_EGRESS_PROVIDER: kafa-egress-1

  edgeless_node1:
    image: ghcr.io/edgeless-project/edgeless_node:v1.0.0
    container_name: edgeless_node_1
    depends_on:
      - edgeless_orc
    environment:
      RUST_LOG: info
      NODE_ID: 22efca65-db0d-4ed7-9b33-1cc7c1513698
      AGENT_HOST: 0.0.0.0
      AGENT_PORT: 7005
      AGENT_URL_ANNOUNCED: http://edgeless_node_1:7005
      INVOCATION_HOST: 0.0.0.0
      INVOCATION_PORT: 7002
      INVOCATION_URL_ANNOUNCED: http://edgeless_node_1:7002
      NODE_REGISTER_URL: http://edgeless_orc:7004 
      SUBSCRIPTION_REFRESH_INTERVAL_SEC: 2
      TELEMETRY_METRICS_HOST: 0.0.0.0
      TELEMETRY_METRICS_PORT: 7003
      TELEMETRY_LOG_LEVEL: info
      TELEMETRY_PERFORMANCE_SAMPLES: true
      WASM_RUNTIME_ENABLED: true
      CONTAINER_RUNTIME_ENABLED: true
      NUM_CORES: 5

  edgeless_node2:
    image: ghcr.io/edgeless-project/edgeless_node:v1.0.0
    container_name: edgeless_node_2
    depends_on:
      - edgeless_orc
    environment:
      RUST_LOG: info
      NODE_ID: 652e6e7d-5a03-4d66-80eb-7e3fa3411e8c
      AGENT_HOST: 0.0.0.0
      AGENT_PORT: 7005
      AGENT_URL_ANNOUNCED: http://edgeless_node_2:7005
      INVOCATION_HOST: 0.0.0.0
      INVOCATION_PORT: 7002
      INVOCATION_URL_ANNOUNCED: http://edgeless_node_2:7002
      NODE_REGISTER_URL: http://edgeless_orc:7004 
      SUBSCRIPTION_REFRESH_INTERVAL_SEC: 2
      TELEMETRY_METRICS_HOST: 0.0.0.0
      TELEMETRY_METRICS_PORT: 7003
      TELEMETRY_LOG_LEVEL: info
      TELEMETRY_PERFORMANCE_SAMPLES: true
      WASM_RUNTIME_ENABLED: true
      CONTAINER_RUNTIME_ENABLED: true
      NUM_CORES: 0
  
  edgeless_node_dda:
    image: ghcr.io/edgeless-project/edgeless_node:v1.0.0
    container_name: edgeless_node_dda
    depends_on:
      - edgeless_orc
    environment:
      RUST_LOG: info
      NODE_ID: 66eaddf2-5121-410b-a004-00bc0bfc85f5
      AGENT_HOST: 0.0.0.0
      AGENT_PORT: 7005
      AGENT_URL_ANNOUNCED: http://edgeless_node_dda:7005
      INVOCATION_HOST: 0.0.0.0
      INVOCATION_PORT: 7002
      INVOCATION_URL_ANNOUNCED: http://edgeless_node_dda:7002
      NODE_REGISTER_URL: http://edgeless_orc:7004 
      SUBSCRIPTION_REFRESH_INTERVAL_SEC: 2
      TELEMETRY_METRICS_HOST: 0.0.0.0
      TELEMETRY_METRICS_PORT: 7003
      TELEMETRY_LOG_LEVEL: info
      TELEMETRY_PERFORMANCE_SAMPLES: true
      WASM_RUNTIME_ENABLED: true
      CONTAINER_RUNTIME_ENABLED: true
      NUM_CORES: 0
      DDA_PROVIDER: dda-1
    
  dda:
    image: ghcr.io/coatyio/dda:latest
    volumes:
      - ./dda/:/dda 
    
  mqtt_broker:
    image: eclipse-mosquitto:latest
    command: mosquitto -c /mosquitto-no-auth.conf
