# NOTE: used to generate docker compose templates for larger edgeless clusters automatically
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379

  edgeless_con:
<<<<<<< Updated upstream:deployment/docker-compose.yml
    image: edgeless_con:latest
||||||| Stash base:deployment/docker-compose.yml
    image: edgeless_con:latest
=======
    image: ghcr.io/edgeless-project/edgeless_con:v1.0.0 
>>>>>>> Stashed changes:scripts/template-docker-compose.yml
    container_name: edgeless_con
    ports:
      - 7001:7001
    environment:
      RUST_LOG: info
      SHOWCONF: 0
      ORCHESTRATOR_ENDPOINT: edgeless_orc:7011
      DOMAIN_REGISTER_ENDPOINT: edgeless_con:7002
      
  edgeless_orc:
<<<<<<< Updated upstream:deployment/docker-compose.yml
    image: edgeless_orc:latest
||||||| Stash base:deployment/docker-compose.yml
    image: edgeless_orc:latest
=======
    image: ghcr.io/edgeless-project/edgeless_orc:v1.0.0 
>>>>>>> Stashed changes:scripts/template-docker-compose.yml
    container_name: edgeless_orc
    depends_on:
      - edgeless_con
      - redis
    environment:
      RUST_LOG: info
      SHOWCONF: 0
      REDIS_ENDPOINT: redis:6379
      ORCHESTRATOR_ENDPOINT: edgeless_orc:7011
      NODE_REGISTER_ENDPOINT: edgeless_orc:7004
      DOMAIN_REGISTER_ENDPOINT: edgeless_con:7002
    ports:
      - 7011:7011
      - 7121:7121
      - 7102:7102
    extra_hosts:
      - "host.docker.internal:host-gateway"


  edgeless_node_file_log:
<<<<<<< Updated upstream:deployment/docker-compose.yml
    image: edgeless_node:latest
||||||| Stash base:deployment/docker-compose.yml
    image: edgeless_node:latest
=======
    image: ghcr.io/edgeless-project/edgeless_node:v1.0.0 
>>>>>>> Stashed changes:scripts/template-docker-compose.yml
    container_name: edgeless_node_file_log
    depends_on:
      - edgeless_orc
    environment:
      RUST_LOG: info
      SHOWCONF: 0
      INVOCATION_ENDPOINT: edgeless_node_file_log:10001
      AGENT_ENDPOINT: edgeless_node_file_log:10002
      NODE_REGISTER_URL: edgeless_orc:7004
      LABELS: '[]'
      NUM_CORES: 1
      NODE_TYPE: FILE_LOG
    ports:
      - 10001:10001
      - 10002:10002
<<<<<<< Updated upstream:deployment/docker-compose.yml


  edgeless_node1:
    image: edgeless_node:latest
    container_name: edgeless_node1
    depends_on:
      - edgeless_orc
    environment:
      RUST_LOG: info
      SHOWCONF: 0
      INVOCATION_ENDPOINT: edgeless_node1:10003
      AGENT_ENDPOINT: edgeless_node1:10004
      NODE_REGISTER_URL: edgeless_orc:7004
      LABELS: '[]'
      NUM_CORES: 1
      NODE_TYPE: WASM
    ports:
      - 10003:10003
      - 10004:10004
||||||| Stash base:deployment/docker-compose.yml


  edgeless_node1:
    image: edgeless_node:latest
    depends_on:
      - edgeless_orc
    environment:
      RUST_LOG: info
      SHOWCONF: 0
      ORCHESTRATOR_ENDPOINT: edgeless_orc:7011
      INVOCATION_ENDPOINT: edgeless_node1:10003
      AGENT_ENDPOINT: edgeless_node1:10004
      LABELS: '[]'
      NUM_CORES: 1
      NODE_TYPE: WASM
    ports:
      - 10003:10003
      - 10004:10004
=======
>>>>>>> Stashed changes:scripts/template-docker-compose.yml
