# SPDX-FileCopyrightText: © 2023 Claudio Cicconetti <c.cicconetti@iit.cnr.it>
# SPDX-FileCopyrightText: © 2024 Siemens AG
# SPDX-License-Identifier: MIT
[workspace]

[profile.release]
lto = true
opt-level = "s"

[package]
name = "edgeless_fractal_demo_http_read_parameters"
version = "0.1.0"
authors = [
    "Claudio Cicconetti <c.cicconetti@iit.cnr.it>",
    "steffen.gerhold@siemens.com",
]
edition = "2021"

[lib]
name = "edgeless_fractal_demo_http_read_parameters"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
edgeless_function = { path = "../../edgeless_function" }
edgeless_http = { path = "../../edgeless_http" }
log = "0.4"
