# SPDX-FileCopyrightText: © 2023 Technical University of Munich, Chair of Connected Mobility
# SPDX-License-Identifier: MIT
[workspace]

[profile.dev]
panic = "abort"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
codegen-units = 1
strip = true

[package]
name = "ping_async"
version = "0.1.0"
authors = ["Raphael Hetzel <hetzel@in.tum.de>"]
edition = "2021"

[lib]
name = "ping_async"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
# edgeless_function = { git = "https://github.com/edgeless-project/edgeless.git", package = "edgeless_function", branch="serverless_ir" }
edgeless_function = {git = "https://github.com/edgeless-project/edgeless.git", branch = "serverless_ir", package = "edgeless_function" }
edgeless_function_core = {git = "https://github.com/edgeless-project/edgeless.git", branch = "serverless_ir", package = "edgeless_function_core" }
# serde = {version="1", features=["derive"] }
# serde_json = "1"
log = "0.4"

[features]

input_pong = []
input_bar = []
output_ping = []
output_baz = []
